go.mod, go.sum, runner/options.go
=> use FileStringSliceVarP for input query

README.md, runner/options.go, runner/runner.go
=> add {{}} markers to field formatting

README.md, runner/options.go, runner/output_writer.go, runner/runner.go
=> search query for specific search engine

runner/options.go
=> fix: quake token env read

uncover/agent/censys/censys.go
```console
echo 'name: "*.arvala7.space" or name: "*.kintan.space"' | ./uncover -e censys -silent
35.202.198.108:80
35.202.198.108:443
35.209.32.112:80
35.209.32.112:443
35.209.79.65:80
35.209.79.65:443
35.222.118.123:80
35.222.118.123:443
104.198.164.172:80
104.198.164.172:443
```
=> included virtual hosts in censys

go.mod, go.sum, runner/runner.go, uncover/agent.go
This PR replaces [go.uber.org/ratelimit ](https://github.com/projectdiscovery/naabu/pull/url)with [projectdiscovery/ratelimit](https://github.com/projectdiscovery/naabu/pull/url).
=> changes for ratelimit library

uncover/agent/zoomeye/zoomeye.go
=> Fixed uncover panic on string port

go.mod, go.sum, integration-tests/source-test.go, runner/options.go, runner/runner.go, uncover/agent/shodanidb/shodan.go
Use [utils](https://github.com/projectdiscovery/utils).
This PR closes #100.
=> Update helper libraries #100

runner/options.go, runner/runner.go, uncover/session.go
- allow cidr/ip input to censys
closes #121
=> adds CIDR/IP input to censys

README.md, runner/options.go, runner/provider.go, runner/runner.go, uncover/agent/hunterhow/hunterhow.go, uncover/agent/hunterhow/request.go, uncover/agent/hunterhow/response.go, uncover/keys.go
```
./uncover -e hunterhow -q 'product.name="jira"' -f host -v  
__  ______  _________ _   _____  _____
/ / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /    
\__,_/_/ /_/\___/\____/|___/\___/_/ v1.0.2
projectdiscovery.io
[hunterhow] community.deiser.com
[hunterhow] jira.deiser.com
[hunterhow] retchat.com
[hunterhow] www.retchat.com
[hunterhow] www.rico-baby.com
[hunterhow] ip74.ip-79-137-122.eu
[hunterhow] team.gitee.cn
```
query guide:
https://hunter.how/guide
=> hunter.how - new api provider support 

sources/agent/fofa/fofa.go, sources/agent/fofa/response.go
```
__  ______  _________ _   _____  _____
/ / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /    
\__,_/_/ /_/\___/\____/|___/\___/_/
projectdiscovery.io
[INF] Current uncover version v1.0.3 (latest)
[fofa] [820031] F点余额不足
```
stdout the fofa error message, eg: connection failure or insufficient fofa points.
=> fofa errmsg

sources/agent/hunterhow/hunterhow.go, sources/session.go
Closes #185 
```console
$ go run . -q hunterhow.query -e hunterhow -l 1000 -o hunterhow.txt -pc providers.yaml -v
__  ______  _________ _   _____  _____
/ / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /
\__,_/_/ /_/\___/\____/|___/\___/_/
projectdiscovery.io
[INF] Current uncover version v1.0.4 (latest)
...
[hunterhow] 45.92.163.84:666
```
=> Fixing max page size

cmd/uncover/uncover.go, runner/output_writer.go, runner/runner.go
=> fix writing result to file

README.md, integration-tests/integration-test.go, integration-tests/source-test.go
Add test case and description on hunter.how
=>   integration-test for hunterhow

integration-tests/integration-test.go, integration-tests/source-test.go, runner/runner.go
=> show raw or json output on default run

go.mod, go.sum
=> Fix build error on `termux`

sources/provider.go
=> fix key check

sources/provider.go
=> Create provider config file if not exists

sources/agent/criminalip/criminalip.go, sources/agent/fofa/fofa.go, sources/agent/google/google.go, sources/agent/hunter/hunter.go, sources/agent/hunterhow/hunterhow.go, sources/agent/netlas/netlas.go, sources/agent/publicwww/publicwww.go, sources/agent/quake/quake.go
Closes #505
```console
$ echo 'domain="google.com"' | go run . -e fofa -r
__  ______  _________ _   _____  _____
/ / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /    
\__,_/_/ /_/\___/\____/|___/\___/_/
projectdiscovery.io
[INF] Current uncover version v1.0.8 (latest)
["142.251.220.78","80","support.google.com"]
["142.251.220.78","80","answers.google.com"]
...
```
=> include partial raw response

README.md, sources/agent/zoomeye/zoomeye.go, sources/provider.go
=> make zoomeye host configurable
